### ISSUE TITLE
Exit Status 125 on Windows 10

### ISSUE THREAD

**Issue by dnc1994** [CorentinB/DeepSort#1]
I'm using Docker Toolbox and PowerShell.

Searching for code 125 tells me that `docker run` itself fails. But I was able to start DeepDetect HTTP server if I only run `docker run beniz/deepdetect_cpu`.

**Comment by dnc1994** [comment]
I guess it could be due to https://github.com/CorentinB/DeepSort/blob/master/deepsort.go#L134 as an absolute path under Windows will contain `:`.

**Comment by CorentinB** [comment]
I think that yes it should be the issue, but I have no Windows environment right now to fix this, either wait for me to fix it or maybe fix it and open a pull request?
Anyway, thanks, I'll look at that!

**Comment by CorentinB** [comment]
I think I have an idea, I'll fix that in the next hours, and commit it for you to test it. :)

**Comment by CorentinB** [comment]
So I removed the automatic docker creation and run, now each user have to start their own deepdetect instance, I explain how to do that easily with docker in 3 commands, in the README, this issue isn't an issue anymore, and you can deal with Windows path during your run process ! :)

I close the issue.
