### ISSUE TITLE
Windows Path Issue

### ISSUE THREAD

**Issue by dnc1994** [CorentinB/DeepSort#2]
Hello it's me again :) Thanks for the work done since my last issue.
Turns out there are still path related issues under Windows. This time I digged a little deeper into the code.

Say my image folder is `C:\Users\dnc1994\images`.

1. Since Windows path contains `:`, to mount a volume I have to use `-v "/c/Users/dnc1994/images:/c/Users/dnc1994/images"`
2. DeepDetect service can be successfully started. Testing it using `curl` also works.
3. Then in deepsort, by getting the absolute path of the input folder (https://github.com/CorentinB/DeepSort/blob/21d756e91206a5717600ac726ac56a280d182103/cmd/deepsort/arguments.go#L30), `arguments.Input` will become `C:\Users\dnc1994\images` again.
4. Container will not be able to use that path, as what exists is `/c/Users/dnc1994/images`.

I can see why you want to have same host & container path. My idea is that, if you were to keep a mapping of host path <-> container path, say we use `-v "/c/Users/dnc1994/images:/images"`. Then when constructing the request for DeepDetect you can transform the host path into container path. 

I also think it will help not only this issue but other future features (e.g. output folder you mentioned).

I understand that Windows path is a mess and this could involve a lot of work. So please take my proposal with a grain of salt. As I'm very new to Golang (only started this afternoon in order to debug your project under Windows, actually), if you want me to work on this I probably need some high level instructions.

Anyway I can always test this under Windows if you like! Many thanks.

**Comment by CorentinB** [comment]
Hello again! Yes it's completely the problem I face actually with the output folder, and it's how it'll be done, thanks for the idea of simply transforming the path, it's so simple that I didn't think about it's, I'm gonna do that.

That's great that you are learning golang, keep learning, I hope to see you doing pull request asap, it's not a complex project but a lot of little things can be done, so it's (I think) a really good first golang project if you want to participate ;)

And great to see that I have a Windows user to test it, keep opening issues for the future commits if you see other bugs, I'll get back to you and I hope close this issue, as soon as the output feature is done, should have fixed this path issue for this feature! 

Have a nice day, thanks again for your participation.

**Comment by CorentinB** [comment]
Hi @dnc1994 , this issue should not be an issue anymore with the last commit, @terorie made a pull request that modify the process of sending images to DeepDetect, now it use **base64** so no need to bind any folder with docker anymore, it will just process your local folder specified with the flag `-i` and send images directly, that should fix your issue, can you confirm?

Thanks.

**Comment by dnc1994** [comment]
That's wonderful news! I'm travelling this week and will be able to test the new solution in two days. Will get back to this issue then. Thank you @CorentinB and @terorie !

**Comment by dnc1994** [comment]
Hi @CorentinB I can confirm that this issue is resolved now. Closing it!
