### ISSUE TITLE
I don't know how to use it next，in docker

### ISSUE THREAD

**Issue by ytgcljj** [CorentinB/DeepSort#5]
Hello, I downloaded docker and executed docker run-d-p 8080:8080 beniz / deepdetect_cpu, but I don't know how to use it next. Thank you! DeepSort do I need to download it in docker?

**Comment by CorentinB** [comment]
Hello @ytgcljj , please follow the [README](https://github.com/CorentinB/DeepSort/blob/master/README.md), and no after starting the container, you need to do everything else outside of the container, on your computer/server directly.

EDIT: please answer back when you will be good with the usage process so I can close this issue.

**Comment by ytgcljj** [comment]
I don't understand if DeepSort is running inside or outside of docker.

**Comment by ytgcljj** [comment]
I did. / DeppSort -- URL http://localhost:8080 -- input INPUT -- output OUTPUT, but I didn't see any difference. It's my picture, isn't it? Please give me a demo picture.

**Comment by ytgcljj** [comment]
![Uploading 4444.jpg…]()

**Comment by ytgcljj** [comment]
![4444](https://user-images.githubusercontent.com/27713475/46596798-473e9880-cb10-11e8-94bd-799064617694.jpg)

**Comment by CorentinB** [comment]
What's your level in computers related stuff?
Looks like maybe DeepSort isn't for you, it's a pretty simple software but need a little understanding on how computers works.

**Comment by ytgcljj** [comment]
Can I have the effect of your AI? I don't understand. I didn't make a mistake, but nothing came out.

**Comment by ytgcljj** [comment]
Excuse me, after running the DOCKER container, do you want to run other programs?

**Comment by CorentinB** [comment]
As said in the README, DeepSort take a folder of picture as an input, and rename them with what DeepDetect (that is running separately in a docker container) find using ResNet or Squeezenet.
